package org.zeroturnaround.jf.homework1;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.Test;

public class MyHomeworkTest {
  private Homework homework;

  @Before
  public void setup() {
    homework = new Homework();
  }

  @Test
  public void testReverse() {
    assertEquals("Input", homework.reverse("tupnI"));
  }

  @Test
  public void testGetCommonSuffix() {
    assertEquals("JavaFundamentals", homework.getCommonSuffix("AmazingJavaFundamentals", "ILoveJavaFundamentals"));
    assertEquals("String", homework.getCommonSuffix("FirstString", "SecondString"));
    assertEquals("dString", homework.getCommonSuffix("SecondString", "ThirdString"));
    assertEquals("g", homework.getCommonSuffix("g", "ThirdString"));
    assertEquals("g", homework.getCommonSuffix("SecondString", "g"));
  }

  @Test
  public void testGetCommonSuffix_noSuffix() {
    assertEquals("", homework.getCommonSuffix("JavaFundamentalsIsAmazing", "ILoveJavaFundamentals"));
    assertEquals("", homework.getCommonSuffix("a", "ILoveJavaFundamentals"));
    assertEquals("", homework.getCommonSuffix("JavaFundamentalsIsAmazing", "l"));
  }

  @Test
  public void testGetCommonSuffix_nullArguments() {
    assertEquals("", homework.getCommonSuffix(null, "ILoveJavaFundamentals"));
    assertEquals("", homework.getCommonSuffix("AmazingJavaFundamentals", null));
    assertEquals("", homework.getCommonSuffix(null, null));
  }

  @Test
  public void testGetCommonSuffix_emptyArguments() {
    assertEquals("", homework.getCommonSuffix("", "ILoveJavaFundamentals"));
    assertEquals("", homework.getCommonSuffix("AmazingJavaFundamentals", ""));
    assertEquals("", homework.getCommonSuffix("", ""));
  }

  @Test
  public void testGetCommonSuffix_superLongArguments() {
    assertEquals("AmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentals", homework.getCommonSuffix("AmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentals", "ILoveJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentalsAmazingJavaFundamentals"));
  }
}
